# Generated by Django 5.2.8 on 2026-09-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_alter_article_is_current_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_html',
            field=models.TextField(blank=True, help_text="Auto-generated when you click 'Fetch from Google Doc'. To change the article text, edit the Google Doc itself and fetch again — edits made directly in this box will be overwritten."),
        ),
        migrations.AlterField(
            model_name='article',
            name='doc_id',
            field=models.CharField(blank=True, help_text="Auto-filled from the link above. You shouldn't need to edit this.", max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='doc_url',
            field=models.TextField(blank=True, help_text='Paste the full Google Doc link here, e.g. https://docs.google.com/document/d/XXXXXXXX/edit'),
        ),
        migrations.AlterField(
            model_name='author',
            name='role',
            field=models.CharField(choices=[('director', 'Director'), ('lead editor', 'Lead Editor'), ('lead publisher', 'Lead Publisher'), ('treasurer', 'Treasurer'), ('social chair', 'Social Chair'), ('writer', 'Writer'), ('contributor', 'Contributor')], default='contributor', max_length=50),
        ),
    ]
