# Generated by Django 5.2.8 on 2026-09-30 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0007_alter_article_content_html_alter_article_doc_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='created_at',
        ),
    ]
