# Generated by Django 5.2.8 on 2026-10-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_remove_article_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_html',
            field=models.TextField(blank=True, help_text='The article text shown on the article page.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='doc_url',
            field=models.TextField(blank=True, help_text='Optional. A Google Doc to import the article text from, e.g. https://docs.google.com/document/d/XXXXXXXX/edit'),
        ),
    ]
