# Generated by Django 5.2.8 on 2026-10-03 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_alter_article_content_html_alter_article_doc_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='headshot',
        ),
    ]
